% Location data
indoors(bedroom).
indoors(break_room).
indoors(close_up_table).
indoors(enormous_bathroom).
indoors(guard_tower).
indoors(locked_stage).
indoors(lonely_tower).
indoors(luxury_theater).
indoors(main_house).
indoors(main_stage).
indoors(meeting_house).
indoors(michelin_starred_cafeteria).
indoors(movie_theater).
indoors(mysterious_mansion).
indoors(observatory).
indoors(piano_room).
indoors(private_library).
indoors(private_suite).
indoors(prop_shop).
indoors(rec_room).
indoors(richest_patients_room).
indoors(screening_room).
indoors(secret_chamber).
indoors(spa).
indoors(waiting_room).
indoors(watertower_bar_grill).
outdoors(ancient_ruins).
outdoors(city_backlot).
outdoors(cliffs).
outdoors(docks).
outdoors(entrance_gate).
outdoors(garden_maze).
outdoors(grounds).
outdoors(haunted_grove).
outdoors(hedge_maze).
outdoors(locked_gate).
outdoors(minigolf_course).
outdoors(roof).
outdoors(screaming_forest).
outdoors(statue_of_midnight).
outdoors(stone_bridge).
outdoors(studio_tour_check_in_stand).
outdoors(tennis_court).
outdoors(upstairs_balcony).
